### ISSUE TITLE
Not PEP8

### ISSUE THREAD

**Issue by mark-adams** [pizzapanther/TwoSpaces#2]
I saw this and I had to file an issue and ask... Why is this not PEP8? :smile:

My editor almost had a heart attack when I opened it and it had two spaces instead of four

**Comment by pizzapanther** [comment]
Guess you didn't see my talk: https://www.youtube.com/watch?v=rDyAIoHDNkU&feature=share

Thought you were there though? Am I just missing the sarcasm?

Anyway, everything is auto-formatted with the PyTexas script: https://github.com/pytexas/PyTexasWeb/blob/master/run_yapf.py

So be messy with your formatting, I'll clean it up in one click. And also you just learned how I named this module.

**Comment by mark-adams** [comment]
Nope, no sarcasm. Just me being dumb and totally forgetting about YAPF. :dizzy_face: 

You're totally right about me being at the talk. I actually found it super useful. I guess I was just so excited about opening up the repo that I missed connecting the talk and the spacing in the repo.

**Comment by pizzapanther** [comment]
Never actually mentioned this repo in the talk but since it is the main driver behind PyTexas I format it the same.

**Comment by mark-adams** [comment]
Ah gotcha! You were right though. The `run_yapf.py` script made things super easy.

Is there some magic trick to doing the frontend build on the PyTexas project?

**Comment by pizzapanther** [comment]
Install directions here: https://github.com/pytexas/PyTexasWeb/blob/master/README.md

But I'm guessing maybe your missing `npm install -g less`, looks like less is listed in the requirements but not in the command list.

I have the dev server setup so it constantly builds the frontend for you. No build step necessary.

**Comment by mark-adams** [comment]
Alright... so I'm not getting many points for paying attention tonight. To be fair, I started working on TwoSpaces and didn't see a README there so I didn't both checking PyTexasWeb. :smiley:

**Comment by pizzapanther** [comment]
I need to properly set this up on pypi too now that there is a contributor!
